/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ActivityHistoryView {
  'at' : Timestamp,
  'id' : bigint,
  'title' : string,
  'owner' : string,
  'kind' : ActivityType,
  'amount' : bigint,
}
export type ActivityType = { 'job' : null } |
  { 'tugas' : null } |
  { 'penarikan' : null };
export interface Cell { 'value' : Value, 'name' : string }
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface Job {
  'id' : bigint,
  'reward' : bigint,
  'title' : string,
  'description' : string,
  'category' : RewardType,
}
export interface LeaderboardEntry {
  'username' : string,
  'rank' : bigint,
  'score' : bigint,
}
export interface LeaderboardPeriod {
  'entries' : Array<LeaderboardEntry>,
  'periodLabel' : string,
  'prizes' : Array<bigint>,
}
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export type RewardType = { 'emailKhusus' : null } |
  { 'emailBebas' : null };
export type TaskStatus = { 'pending' : null } |
  { 'diterima' : null };
export interface TaskView {
  'id' : bigint,
  'status' : TaskStatus,
  'reward' : bigint,
  'owner' : string,
  'createdAt' : Timestamp,
  'jobId' : bigint,
  'category' : RewardType,
}
export type Timestamp = bigint;
export interface UserProfileView {
  'principal' : string,
  'name' : string,
  'email' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface WalletView {
  'total' : bigint,
  'owner' : string,
  'rewardEmailKhusus' : bigint,
  'rewardEmailBebas' : bigint,
}
export type WithdrawalStatus = { 'diproses' : null } |
  { 'selesai' : null } |
  { 'diajukan' : null };
export interface WithdrawalView {
  'at' : Timestamp,
  'id' : bigint,
  'status' : WithdrawalStatus,
  'method' : string,
  'owner' : string,
  'nominal' : bigint,
}
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'completeTask' : ActorMethod<[bigint], [] | [TaskView]>,
  'execute' : ActorMethod<[string], Result>,
  'getCallerProfile' : ActorMethod<[], [] | [UserProfileView]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getHomeSummary' : ActorMethod<
    [],
    {
      'pendingCount' : bigint,
      'diterimaCount' : bigint,
      'rewardEmailKhusus' : bigint,
      'saldo' : bigint,
      'rewardEmailBebas' : bigint,
    }
  >,
  'getJob' : ActorMethod<[bigint], [] | [Job]>,
  'getMyProfileStats' : ActorMethod<
    [],
    {
      'totalRewardEarned' : bigint,
      'totalJobsCompleted' : bigint,
      'currentRank' : bigint,
    }
  >,
  'getMyTask' : ActorMethod<[bigint], [] | [TaskView]>,
  'getMyWallet' : ActorMethod<[], WalletView>,
  'getWeeklyLeaderboard' : ActorMethod<[], LeaderboardPeriod>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listJobs' : ActorMethod<[], Array<Job>>,
  'listJobsByCategory' : ActorMethod<[RewardType], Array<Job>>,
  'listMyHistory' : ActorMethod<[], Array<ActivityHistoryView>>,
  'listMyHistoryByKind' : ActorMethod<
    [ActivityType],
    Array<ActivityHistoryView>
  >,
  'listMyTasks' : ActorMethod<[], Array<TaskView>>,
  'listMyWithdrawals' : ActorMethod<[], Array<WithdrawalView>>,
  'requestWithdrawal' : ActorMethod<[bigint, string], WithdrawalView>,
  'schema' : ActorMethod<[], string>,
  'takeJob' : ActorMethod<[bigint], [] | [TaskView]>,
  'updateCallerName' : ActorMethod<[string], UserProfileView>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];