/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const TaskStatus = IDL.Variant({
  'pending' : IDL.Null,
  'diterima' : IDL.Null,
});
export const Timestamp = IDL.Nat;
export const RewardType = IDL.Variant({
  'emailKhusus' : IDL.Null,
  'emailBebas' : IDL.Null,
});
export const TaskView = IDL.Record({
  'id' : IDL.Nat,
  'status' : TaskStatus,
  'reward' : IDL.Nat,
  'owner' : IDL.Text,
  'createdAt' : Timestamp,
  'jobId' : IDL.Nat,
  'category' : RewardType,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const UserProfileView = IDL.Record({
  'principal' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
});
export const Job = IDL.Record({
  'id' : IDL.Nat,
  'reward' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'category' : RewardType,
});
export const WalletView = IDL.Record({
  'total' : IDL.Nat,
  'owner' : IDL.Text,
  'rewardEmailKhusus' : IDL.Nat,
  'rewardEmailBebas' : IDL.Nat,
});
export const LeaderboardEntry = IDL.Record({
  'username' : IDL.Text,
  'rank' : IDL.Nat,
  'score' : IDL.Nat,
});
export const LeaderboardPeriod = IDL.Record({
  'entries' : IDL.Vec(LeaderboardEntry),
  'periodLabel' : IDL.Text,
  'prizes' : IDL.Vec(IDL.Nat),
});
export const ActivityType = IDL.Variant({
  'job' : IDL.Null,
  'tugas' : IDL.Null,
  'penarikan' : IDL.Null,
});
export const ActivityHistoryView = IDL.Record({
  'at' : Timestamp,
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'owner' : IDL.Text,
  'kind' : ActivityType,
  'amount' : IDL.Nat,
});
export const WithdrawalStatus = IDL.Variant({
  'diproses' : IDL.Null,
  'selesai' : IDL.Null,
  'diajukan' : IDL.Null,
});
export const WithdrawalView = IDL.Record({
  'at' : Timestamp,
  'id' : IDL.Nat,
  'status' : WithdrawalStatus,
  'method' : IDL.Text,
  'owner' : IDL.Text,
  'nominal' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'completeTask' : IDL.Func([IDL.Nat], [IDL.Opt(TaskView)], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getCallerProfile' : IDL.Func([], [IDL.Opt(UserProfileView)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getHomeSummary' : IDL.Func(
      [],
      [
        IDL.Record({
          'pendingCount' : IDL.Nat,
          'diterimaCount' : IDL.Nat,
          'rewardEmailKhusus' : IDL.Nat,
          'saldo' : IDL.Nat,
          'rewardEmailBebas' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getJob' : IDL.Func([IDL.Nat], [IDL.Opt(Job)], ['query']),
  'getMyProfileStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalRewardEarned' : IDL.Nat,
          'totalJobsCompleted' : IDL.Nat,
          'currentRank' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getMyTask' : IDL.Func([IDL.Nat], [IDL.Opt(TaskView)], ['query']),
  'getMyWallet' : IDL.Func([], [WalletView], ['query']),
  'getWeeklyLeaderboard' : IDL.Func([], [LeaderboardPeriod], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listJobs' : IDL.Func([], [IDL.Vec(Job)], ['query']),
  'listJobsByCategory' : IDL.Func([RewardType], [IDL.Vec(Job)], ['query']),
  'listMyHistory' : IDL.Func([], [IDL.Vec(ActivityHistoryView)], ['query']),
  'listMyHistoryByKind' : IDL.Func(
      [ActivityType],
      [IDL.Vec(ActivityHistoryView)],
      ['query'],
    ),
  'listMyTasks' : IDL.Func([], [IDL.Vec(TaskView)], ['query']),
  'listMyWithdrawals' : IDL.Func([], [IDL.Vec(WithdrawalView)], ['query']),
  'requestWithdrawal' : IDL.Func([IDL.Nat, IDL.Text], [WithdrawalView], []),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'takeJob' : IDL.Func([IDL.Nat], [IDL.Opt(TaskView)], []),
  'updateCallerName' : IDL.Func([IDL.Text], [UserProfileView], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const TaskStatus = IDL.Variant({
    'pending' : IDL.Null,
    'diterima' : IDL.Null,
  });
  const Timestamp = IDL.Nat;
  const RewardType = IDL.Variant({
    'emailKhusus' : IDL.Null,
    'emailBebas' : IDL.Null,
  });
  const TaskView = IDL.Record({
    'id' : IDL.Nat,
    'status' : TaskStatus,
    'reward' : IDL.Nat,
    'owner' : IDL.Text,
    'createdAt' : Timestamp,
    'jobId' : IDL.Nat,
    'category' : RewardType,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const UserProfileView = IDL.Record({
    'principal' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
  });
  const Job = IDL.Record({
    'id' : IDL.Nat,
    'reward' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'category' : RewardType,
  });
  const WalletView = IDL.Record({
    'total' : IDL.Nat,
    'owner' : IDL.Text,
    'rewardEmailKhusus' : IDL.Nat,
    'rewardEmailBebas' : IDL.Nat,
  });
  const LeaderboardEntry = IDL.Record({
    'username' : IDL.Text,
    'rank' : IDL.Nat,
    'score' : IDL.Nat,
  });
  const LeaderboardPeriod = IDL.Record({
    'entries' : IDL.Vec(LeaderboardEntry),
    'periodLabel' : IDL.Text,
    'prizes' : IDL.Vec(IDL.Nat),
  });
  const ActivityType = IDL.Variant({
    'job' : IDL.Null,
    'tugas' : IDL.Null,
    'penarikan' : IDL.Null,
  });
  const ActivityHistoryView = IDL.Record({
    'at' : Timestamp,
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'owner' : IDL.Text,
    'kind' : ActivityType,
    'amount' : IDL.Nat,
  });
  const WithdrawalStatus = IDL.Variant({
    'diproses' : IDL.Null,
    'selesai' : IDL.Null,
    'diajukan' : IDL.Null,
  });
  const WithdrawalView = IDL.Record({
    'at' : Timestamp,
    'id' : IDL.Nat,
    'status' : WithdrawalStatus,
    'method' : IDL.Text,
    'owner' : IDL.Text,
    'nominal' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'completeTask' : IDL.Func([IDL.Nat], [IDL.Opt(TaskView)], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getCallerProfile' : IDL.Func([], [IDL.Opt(UserProfileView)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getHomeSummary' : IDL.Func(
        [],
        [
          IDL.Record({
            'pendingCount' : IDL.Nat,
            'diterimaCount' : IDL.Nat,
            'rewardEmailKhusus' : IDL.Nat,
            'saldo' : IDL.Nat,
            'rewardEmailBebas' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getJob' : IDL.Func([IDL.Nat], [IDL.Opt(Job)], ['query']),
    'getMyProfileStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalRewardEarned' : IDL.Nat,
            'totalJobsCompleted' : IDL.Nat,
            'currentRank' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getMyTask' : IDL.Func([IDL.Nat], [IDL.Opt(TaskView)], ['query']),
    'getMyWallet' : IDL.Func([], [WalletView], ['query']),
    'getWeeklyLeaderboard' : IDL.Func([], [LeaderboardPeriod], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listJobs' : IDL.Func([], [IDL.Vec(Job)], ['query']),
    'listJobsByCategory' : IDL.Func([RewardType], [IDL.Vec(Job)], ['query']),
    'listMyHistory' : IDL.Func([], [IDL.Vec(ActivityHistoryView)], ['query']),
    'listMyHistoryByKind' : IDL.Func(
        [ActivityType],
        [IDL.Vec(ActivityHistoryView)],
        ['query'],
      ),
    'listMyTasks' : IDL.Func([], [IDL.Vec(TaskView)], ['query']),
    'listMyWithdrawals' : IDL.Func([], [IDL.Vec(WithdrawalView)], ['query']),
    'requestWithdrawal' : IDL.Func([IDL.Nat, IDL.Text], [WithdrawalView], []),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'takeJob' : IDL.Func([IDL.Nat], [IDL.Opt(TaskView)], []),
    'updateCallerName' : IDL.Func([IDL.Text], [UserProfileView], []),
  });
};

export const init = ({ IDL }) => { return []; };